// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr63t0SvpTIkAYeaoNPOQcppXSkRdF3rg',
    appId: '1:893259343277:web:3cbb1e97f41c707a986d24',
    messagingSenderId: '893259343277',
    projectId: 'weebstore-77611',
    authDomain: 'weebstore-77611.firebaseapp.com',
    databaseURL: 'https://weebstore-77611-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weebstore-77611.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALHoZRc9iIuqoRi8KJB1N3nl8sTLDfSuo',
    appId: '1:893259343277:android:97a08210b6f5a916986d24',
    messagingSenderId: '893259343277',
    projectId: 'weebstore-77611',
    databaseURL: 'https://weebstore-77611-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weebstore-77611.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ol_WhCcyrpkOWVkgChfjwE5z05O1RU8',
    appId: '1:893259343277:ios:c1d5ee04f0c4ecdb986d24',
    messagingSenderId: '893259343277',
    projectId: 'weebstore-77611',
    databaseURL: 'https://weebstore-77611-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weebstore-77611.appspot.com',
    iosClientId: '893259343277-7i7c0fug35tt200osp7fermis8r3mv1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.wildersmerch',
  );
}
